# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-04 02:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField()),
                ('title', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('course_num', models.CharField(max_length=10)),
                ('year', models.SmallIntegerField()),
                ('semester', models.SmallIntegerField()),
                ('instructor', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField()),
                ('title', models.CharField(max_length=500, null=True)),
                ('content_markdown', models.TextField()),
                ('content_html', models.TextField()),
                ('parent_chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursenotes.Chapter')),
            ],
        ),
        migrations.CreateModel(
            name='TextBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursenotes.Course')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='parent_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursenotes.TextBook'),
        ),
        migrations.AddField(
            model_name='author',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursenotes.TextBook'),
        ),
    ]
