# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursenotes', '0002_auto_20160904_0241'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='notes/images')),
            ],
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(blank=True, default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sectionimage',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursenotes.Section'),
        ),
    ]
