# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 04:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursenotes', '0003_auto_20160915_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coursenotes.Course'),
        ),
    ]
