# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 04:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursenotes', '0004_chapter_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursenotes.Course'),
        ),
    ]
