# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 20:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursenotes', '0005_auto_20170103_0455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='parent_book',
        ),
    ]
