# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=11)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('description', models.TextField()),
                ('categories', models.ManyToManyField(to='finance.Category')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.Retailer')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.TransactionMethod'),
        ),
    ]
